import React from 'react';
import { Copy, Share2, ChevronRight, Activity } from 'lucide-react';

const ReviewScreen = ({ entries }) => {
  const copyWeeklyReport = () => {
    if (entries.length === 0) return;

    // Get last 7 days of entries
    const recentEntries = entries
      .sort((a, b) => new Date(b.date) - new Date(a.date))
      .slice(0, 7);

    let report = "# Weekly Readiness & Movement Report\n\n";
    
    recentEntries.forEach(e => {
      const dateStr = new Date(e.date).toLocaleDateString();
      report += `## ${dateStr}\n`;
      report += `- **Readiness Score:** ${e.recommendation.score}\n`;
      report += `- **Track:** ${e.recommendation.track}\n`;
      report += `- **Energy:** ${e.checkIn.physicalEnergy} (P), ${e.checkIn.mentalEnergy} (M)\n`;
      report += `- **Pain/Stiffness:** ${e.checkIn.overallPain} / ${e.checkIn.overallStiffness}\n`;
      if (e.recommendation.priorityAreas.length > 0) {
        report += `- **Priority Areas:** ${e.recommendation.priorityAreas.join(', ')}\n`;
      }
      if (e.reflection) {
        report += `- **Reflection:** ${e.reflection.whatChanged}\n`;
        report += `- **Tomorrow Focus:** ${e.reflection.tomorrow}\n`;
      }
      report += "\n";
    });

    report += "---\nGenerated by The Practice MVP";

    navigator.clipboard.writeText(report).then(() => {
      alert('Weekly report copied to clipboard!');
    });
  };

  return (
    <div className="space-y-8 animate-in fade-in duration-500">
      <div className="flex justify-between items-end">
        <div className="space-y-1">
          <h2 className="text-3xl font-black text-slate-900">Review</h2>
          <p className="text-slate-500 font-medium">Your movement history.</p>
        </div>
        <button 
          onClick={copyWeeklyReport}
          disabled={entries.length === 0}
          className="p-3 bg-blue-50 text-blue-600 rounded-xl border border-blue-100 flex items-center gap-2 font-bold text-sm"
        >
          <Copy size={18} />
          Copy Weekly Report
        </button>
      </div>

      {entries.length === 0 ? (
        <div className="bg-white rounded-2xl p-12 text-center border-2 border-dashed border-slate-200">
          <Activity size={48} className="mx-auto text-slate-300 mb-4" />
          <p className="text-slate-500 font-medium">No entries yet. Start your first check-in today.</p>
        </div>
      ) : (
        <div className="space-y-4">
          {entries
            .sort((a, b) => new Date(b.date) - new Date(a.date))
            .map((entry, idx) => (
              <div key={idx} className="bg-white rounded-2xl p-5 border border-slate-200 shadow-sm flex justify-between items-center group">
                <div className="space-y-1">
                  <div className="text-xs font-black text-slate-400 uppercase tracking-widest">
                    {new Date(entry.date).toLocaleDateString('en-US', { month: 'short', day: 'numeric', weekday: 'short' })}
                  </div>
                  <div className="flex items-center gap-2">
                    <div className={`w-3 h-3 rounded-full ${
                      entry.recommendation.track === 'Green' ? 'bg-green-500' : 
                      entry.recommendation.track === 'Yellow' ? 'bg-yellow-500' : 'bg-red-500'
                    }`} />
                    <span className="font-bold text-slate-800">{entry.recommendation.track} Track</span>
                    <span className="text-slate-400 text-sm font-medium">• Score: {entry.recommendation.score}</span>
                  </div>
                  {entry.reflection && (
                    <p className="text-sm text-slate-600 italic line-clamp-1 mt-1 pr-4">
                      "{entry.reflection.whatChanged || entry.reflection.tomorrow}"
                    </p>
                  )}
                </div>
                <ChevronRight size={20} className="text-slate-300 group-active:text-blue-500 transition-colors" />
              </div>
            ))}
        </div>
      )}
    </div>
  );
};

export default ReviewScreen;
